bfac_shift: 0.8
bfac_width: 50.0
bilayer_eq: false
box:
- 25.0
- 25.0
- 150.0
colabfold: 1
cutoff_lj: 2.0
cutoff_restr: 0.9
cutoff_yu: 4.0
eps_lj: 0.2
fdomains: /maps/projects/prism/people/bqm193/runs/try_calvados/monica_extra_sim/constraints_999/2q76_Fv_DC_constraints.yaml
ffasta: fastabib.fasta
fixed_lambda: 0
fresidues: /projects/prism/people/bqm193/software/CALVADOS/residues_C3.csv
frestart: restart.chk
friction_coeff: 0.01
gpu_id: 0
ionic: 0.15
k_eq: 0.02
k_go: 10.0
k_harmonic: 700
kb: 8033.0
pH: 7.0
pae_shift: 0.4
pae_width: 8.0
pdb_folder: /maps/projects/prism/people/bqm193/runs/try_calvados/monica_extra_sim/imgt2calvados
platform: CPU
restart: null
restraint_type: harmonic
runtime: 0
slab_eq: false
slab_outer: 30
slab_width: 20
steps: 10050000
steps_eq: 1000
sysname: 2q76_Fv_DC
temp: 298
threads: 4
topol: slab
use_com: true
verbose: true
wfreq: 10000
zero_lateral_tension: false
